/**
 * Copies ZAO's fonts into dist/fonts and writes dist/fonts.css.
 *
 * - Geist and Geist Mono come from the `geist` npm package, which keeps all
 *   OpenType features (the Google Fonts files drop most of them).
 * - Newsreader comes from Fontsource (Latin and Latin Extended, with the
 *   weight and optical-size axes).
 * - Fallback faces use Capsize metrics so the swap from the system font to the
 *   webfont doesn't shift layout.
 *
 * Run with: pnpm --filter @zao/react build
 */
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { createFontStack } from '@capsizecss/core';
import geistMetrics from '@capsizecss/metrics/geist';
import newsreaderMetrics from '@capsizecss/metrics/newsreader';
import arialMetrics from '@capsizecss/metrics/arial';
import georgiaMetrics from '@capsizecss/metrics/georgia';

const pkg = new URL('../', import.meta.url);
const modules = new URL('node_modules/', pkg);
const out = new URL('dist/fonts/', pkg);
await mkdir(out, { recursive: true });

const copy = async (from: URL, name: string) => copyFile(from, new URL(name, out));

// Geist and Geist Mono
const geist = new URL('geist/dist/fonts/', modules);
await copy(new URL('geist-sans/Geist-Variable.woff2', geist), 'Geist-Variable.woff2');
await copy(new URL('geist-mono/GeistMono-Variable.woff2', geist), 'GeistMono-Variable.woff2');
await copy(new URL('geist/LICENSE.txt', modules), 'Geist-OFL.txt');

// Newsreader: reuse Fontsource's subsets and unicode ranges, renamed to "Newsreader".
const fontsource = new URL('@fontsource-variable/newsreader/', modules);
const fontsourceCss = await readFile(new URL('opsz.css', fontsource), 'utf8');
const newsreaderFaces: string[] = [];
for (const subset of ['latin-ext', 'latin']) {
  const file = `newsreader-${subset}-opsz-normal.woff2`;
  const block = fontsourceCss.split('@font-face').find((b) => b.includes(file));
  const range = block?.match(/unicode-range:\s*([^;]+);/)?.[1];
  if (!range)
    throw new Error(`Could not find the ${subset} subset in @fontsource-variable/newsreader`);
  await copy(new URL(`files/${file}`, fontsource), file);
  newsreaderFaces.push(`@font-face {
  font-family: "Newsreader";
  font-style: normal;
  font-weight: 200 800;
  font-display: swap;
  src: url("./fonts/${file}") format("woff2");
  unicode-range: ${range};
}`);
}
await copy(new URL('LICENSE', fontsource), 'Newsreader-OFL.txt');

// Metric-matched fallbacks
const fallbacks = [
  createFontStack([geistMetrics, arialMetrics]),
  createFontStack([newsreaderMetrics, georgiaMetrics]),
].flatMap((stack) => stack.fontFaces.split('\n\n').filter(Boolean));

const css = `/*
 * ZAO fonts. Generated by scripts/build-fonts.ts; do not edit.
 * Geist and Geist Mono (Vercel) and Newsreader (Production Type) are licensed
 * under the SIL Open Font License 1.1. See the license files in ./fonts.
 */

@font-face {
  font-family: "Geist";
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url("./fonts/Geist-Variable.woff2") format("woff2");
}

@font-face {
  font-family: "Geist Mono";
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url("./fonts/GeistMono-Variable.woff2") format("woff2");
}

${newsreaderFaces.join('\n\n')}

/* Fallbacks sized to match the webfonts, so the swap doesn't shift layout. */
${fallbacks.join('\n\n')}
`;

await writeFile(new URL('dist/fonts.css', pkg), css);
console.log('Wrote dist/fonts.css and copied 5 font files.');
