import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';
import { generatePaletteDocuments } from '@zao/engine/palette';
import { finishes } from '../palette.config.ts';

const baselineHashes: Record<string, string> = {
  su: '3fbeb826db4ac693da4f927af6ae429d67904231e2553166b3395c4897405b65',
  yu: '1511e4cb6a4a5cac51a70fc37f9af92d8deb2ba8568f45f7ab4c4828f419438f',
};

describe('palette generator preserves its original output', () => {
  it('produces byte-identical files with default generator options', async () => {
    const { documents } = generatePaletteDocuments(finishes);
    for (const finish of Object.keys(baselineHashes)) {
      const output = JSON.stringify(documents[finish], null, 2) + '\n';
      const digest = createHash('sha256').update(output).digest('hex');
      const checkedIn = await readFile(
        new URL(`../src/palettes/${finish}.generated.tokens.json`, import.meta.url),
        'utf8',
      );
      expect(digest, `${finish} generated bytes`).toBe(baselineHashes[finish]);
      expect(output, `${finish} checked-in bytes`).toBe(checkedIn);
    }
  });
});
