/**
 * Writes resolved tokens for every shipped context to dist/json/<context>.json,
 * plus dist/index.js with the token list, for docs, tests and agents.
 *
 * Runs after `tz build` (see package.json).
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { defineConfig, parse, type TokenNormalized } from '@terrazzo/parser';
import { contexts, cssVar } from '../contexts.ts';

const root = new URL('../', import.meta.url);
const resolverUrl = new URL('src/zao.resolver.json', root);

export async function loadResolver() {
  const config = defineConfig({ tokens: [resolverUrl.href], alphabetize: false }, { cwd: root });
  const src = await readFile(resolverUrl, 'utf8');
  const { resolver } = await parse([{ filename: resolverUrl, src }], {
    config,
    req: async (url) => readFile(url, 'utf8'),
  });
  return resolver;
}

/** A plain CSS string for a resolved token value. */
export function cssValue(token: TokenNormalized): string {
  const v = token.$value as unknown;
  const dim = (d: { value: number; unit: string }) => `${d.value}${d.unit}`;
  const color = (c: { colorSpace: string; components: (number | 'none')[]; alpha?: number }) => {
    const parts = c.components
      .map((n) => (typeof n === 'number' ? Number(n.toFixed(4)) : n))
      .join(' ');
    const alpha = c.alpha !== undefined && c.alpha < 1 ? ` / ${c.alpha}` : '';
    return c.colorSpace === 'srgb'
      ? `color(srgb ${parts}${alpha})`
      : `${c.colorSpace}(${parts}${alpha})`;
  };
  switch (token.$type) {
    case 'color':
      return color(v as Parameters<typeof color>[0]);
    case 'dimension':
    case 'duration':
      return dim(v as { value: number; unit: string });
    case 'fontFamily':
      return (v as string[]).map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ');
    case 'cubicBezier':
      return `cubic-bezier(${(v as number[]).join(', ')})`;
    case 'shadow':
      return (v as Array<Record<string, unknown>>)
        .map((s) =>
          [
            s.inset ? 'inset' : '',
            dim(s.offsetX as never),
            dim(s.offsetY as never),
            dim(s.blur as never),
            dim(s.spread as never),
            color(s.color as never),
          ]
            .filter(Boolean)
            .join(' '),
        )
        .join(', ');
    default:
      return typeof v === 'object' ? JSON.stringify(v) : String(v);
  }
}

async function main() {
  const resolver = await loadResolver();
  const outDir = new URL('dist/json/', root);
  await mkdir(outDir, { recursive: true });

  let ids: string[] = [];
  for (const ctx of contexts) {
    const tokens = resolver.apply({ theme: ctx.theme, mode: ctx.mode });
    // Keep source order, so docs list tokens the way the source files group them.
    const entries = Object.values(tokens);
    ids = entries.map((t) => t.id);
    const json = {
      context: ctx,
      tokens: Object.fromEntries(
        entries.map((t) => [
          t.id,
          {
            type: t.$type,
            cssVar: cssVar(t.id),
            value: t.$type === 'typography' ? t.$value : cssValue(t),
            ...(t.aliasOf ? { aliasOf: t.aliasOf } : {}),
            ...(t.$description ? { description: t.$description } : {}),
          },
        ]),
      ),
    };
    await writeFile(new URL(`${ctx.id}.json`, outDir), JSON.stringify(json, null, 2) + '\n');
  }

  const index = `// Generated by scripts/export-json.ts. Do not edit.
export const contexts = ${JSON.stringify(contexts, null, 2)};
export const tokenIds = ${JSON.stringify(ids, null, 2)};
export const cssVar = (id) => \`--zao-\${id.replaceAll('.', '-')}\`;
`;
  const types = `// Generated by scripts/export-json.ts. Do not edit.
export declare const contexts: ${JSON.stringify(contexts)};
export type Context = (typeof contexts)[number];
export type ContextId = Context['id'];
export type Theme = Context['theme'];
export type Mode = Context['mode'];
export type TokenId = ${ids.map((id) => JSON.stringify(id)).join(' | ')};
export declare const tokenIds: TokenId[];
export declare const cssVar: (id: TokenId) => string;
`;
  await writeFile(new URL('dist/index.js', root), index);
  await writeFile(new URL('dist/index.d.ts', root), types);
  console.log(`Exported ${ids.length} tokens for ${contexts.map((c) => c.id).join(', ')}.`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  await main();
}
